models/DataList.php
models/base/Organization.php

El proposito de esos cambios es para garantizar la insercion de nuevas organizacion

Organizacion create

---

models/Attendance.php
models/Event.php
models/base/Attendance.php
models/base/Event.php
views/event/_list.php

esto arregla el listado de eventos con su pais, usando el "id", no estoy seguro si daña algo de lo ya "parchado" antes.

fix attendance country listed in an event

---

controllers/GraphicController.php

Al realizar la separacion del campo product en la tabla de project_contact las consulta que enviaban los datos a los graficos estadisticos se dañaron, se corrijo agregando la relacion de project_contact y monitoring_product

Errores debido a la creacion de monitoring_product

---

controllers/ProjectController.php

Fix nullsfirst

---

models/Event.php
models/base/Event.php
models/search/Event.php
views/event/_form.php

se renombro  campo implementing_organization_id a organization_id de la entidad even en los siguientes archivos
models/Event.php
models/base/Event.php
models/search/Event.php
views/event/_form.php

renombramiento de campo en model, controller, view, de la entida even

---

controllers/GraphicController.php
controllers/ImportController.php
controllers/OptController.php
models/base/Organization.php

Este cambio de renombramiento de campo (implementing_organization_id a organization_id) de la entidad event en el archivo GraphicController.php,
ya se habia subido el dia de ayer, por lo cual este archivo ya implementa este cambio, pero evidentemente master tomo este cambio.

Estadisitica organizacion

---

controllers/ImportController.php
controllers/ReportController.php
models/Attendance.php
models/Contact.php
models/Event.php
models/MonitoringContactType.php
models/MonitoringEducation.php
models/MonitoringProduct.php
models/ProjectContact.php
models/base/MonitoringContactType.php
models/base/MonitoringEducation.php
models/base/MonitoringProduct.php
models/base/ProjectContact.php
vendor/yiisoft/yii2/helpers/BaseJson.php

Se realizaron cambios en el consumo de catalogos de la tabla data_list por los catalogos independientes tales como monitoring_education, monitoring_type y monitoring_product. A su vez se corrigio en backend de manipulacion de datos provenientes del excel conforme a la nueva estructura de base de datos, se agregaron los modelos que representan a las nuevas tablas catalogos antes mencioandas

Correccion en la importacion de beneficiarios provenientes de excel

---

models/Attendance.php

Se corrigió fixed al guardar registro attendance. 
Se modificó archivo models/attendance.php
Metodo modificado rules()
linea [['fullname'], 'required'] fué comentada

moficacion de regla en modelo attendance

---

controllers/GraphicController.php
controllers/OptController.php

Se corrigió url graphic/dashboard error al obtener tipos de participantes debido a que hacia referencia en la consulta a data_list
Archivo modificado GraphicController.php 
metodo ParticipantesTipoSexoSubquery
linea 880 
se cambio referencia data_list por monitoring_contacttype

Fix data list in tipoparticipantes dashboard

---

models/DataList.php

los cambios realizados en los commits son para el metodo itemsBySlug consulta mediante query builder a la tabla country para obtener listado de paises, y para CountryCode correccion en la condicional del if, ya que query builder si trae datos en esta caso envia un array de ser caso contrario un false

Error data list country

---

components/UCatalogo.php
models/DataList.php
models/base/Organization.php

correccion de guardo/actualiacion y vista de detalles de organization, comentareo de relacion de organization con datalist evitaba la insercion/ actualizacion de una organizacion

correccion de guardo/actualiacion y vista de detalles de organization

---

controllers/ImportController.php

Reverts LutheranWorldRelief/monitoreo_lac#33

Revert "correccion al buscar si la educacion de un participantes en monitorin…"

---

components/UCatalogo.php
controllers/ContactController.php
models/Attendance.php
models/Contact.php
models/DataList.php
models/MonitoringContactType.php
models/MonitoringEducation.php
models/base/Contact.php
views/contact/_form.php
views/contact/index.php

Correccion de view contac, en mostrar, actualizar 
Se hizo midificaciones de la entidad data_list por monitoringContactType, monitoringEducation
en vista, model, controller
Modificados
modified:   models/Attendance.php
modified:   models/MonitoringContactType.php
modified:   models/MonitoringEducation.php
modified:   views/contact/_form.php

Fix contact error

---

controllers/ImportController.php
models/MonitoringEducation.php
views/import/beneficiarios/step-2.php

Correccion en la vista de paso 2 de importancion, y aplicada observacion realizada para validar si existe viene una nueva educacion o no desde el excel

Fix last merge

---

models/Country.php
models/base/Country.php
models/base/Event.php
models/base/Organization.php

Se agrego modelo country en 
models/country.php y models/base/country.php
Se modifico archivos estableciendo relacion en metodo rules() con modelo country
se reemplazo data_list por modelo country
modified:   models/base/Event.php
modified:   models/base/Organization.php

Agregando modelo country

---

models/Country.php
views/contact/_form.php
views/contact/index.php
views/event/_form.php
views/import/beneficiarios/step-2.php
web/js/event.form.js

Los cambios realizados consisten en utilizar en los formularios y vistas de detalle , las funciones correspondientes a cada catalogo en uso.

Migrar datalist country

---

models/AuthUser.php

correccion de campo value x id, ya que se realizo el cambio de realizar la consulta de los paises de data list x country.

correccion en funcion countriesModels consume datos de modelo Country

---

controllers/OptController.php
controllers/ReportController.php
views/contact/index.php

-correccion en nombramiento de parametro country x country_id
-reemplazo de consultar con funcion de datalist a funcion de country

Error reporte y duplicados

---

controllers/ImportController.php
models/Contact.php

los cambios realizados para este PR, son validaciones de valores que viene del excel y el backend no sabia como resolver para permitir una correcta importacion de datos. PD Problemas con la opcion de fusionar

Garantia formato excel

---

config/params.php
config/web.php
controllers/SiteController.php

si la sesion de django está activa hace login automaticamente uasndo el mismo username

autologin if django session is active

---

components/UCatalogo.php
components/UExcelBeneficiario.php
controllers/DataListController.php
controllers/ImportController.php
controllers/ReportController.php
models/Contact.php
models/DataList.php
models/Event.php
models/LoginForm.php
models/Organization.php
models/base/Attendance.php
models/base/Contact.php
models/base/Event.php
models/base/Filter.php
models/base/Organization.php
models/base/OrganizationType.php
models/base/Project.php
models/base/SqlContactEvent.php
models/base/SqlEvent.php
models/base/SqlProject.php
models/base/SqlUsuario.php
models/base/Structure.php
models/form/ReportForm.php
modules/seguridad/views/menu/_menu.php
views/event/_form.php
views/filter/_subform.php
views/graphic/dashboard/filtros.php
views/import/beneficiarios/step-2.php
views/import/beneficiarios/wizard.php

Corrigiendo errores de sintaxis que hacian quebrar la aplicacion y se agrego use yii; en archivos que no reconocia el valor de la sintaxis..

Corrigiendo errores de archivos con sintaxis erroneas

---

controllers/CrudangularController.php
controllers/OptController.php
controllers/SiteController.php
messages/en/messages.po
messages/es/messages.po
messages/fr/messages.po
views/import/beneficiarios/step-2.php
views/opt/_contact_merge_modal.php

Corrigiendo archivos y .po para los idiomas en las sintaxis.. se borro la sintaxis y se corrio nuevamente el comando para generarlo automaticamente ./yii message/extract para los 3 idiomas

Fix translate

---

controllers/SiteController.php
models/LoginForm.php

validación cuando usuario inicia sesión con cuenta de microsoft, se verifica que exista en auth_user yii.
ya que cuando no se encontraba se obtenía un error de no es posible asignar sesión a un usuario null

validando que usuario exista en auth_user yii

---

models/LoginForm.php

Si sesión existe en django se realiza la búsqueda de usuario por username o campo email.
Nota. En la tabla de auth_user de yii2 ya existe el campo email donde se registra el correo del usuario,
por lo tanto no se ha realizado ninguna modificación en esta tabla.

buscar usuario por username or mail

---

components/TranslateStringJs.php
controllers/TranslateStringJsController.php
web/js/script/dashboard_index.js

Traducción de archivo js dependiendo de idioma del usuario con sesion iniciada
Se creó dos nuevos archivos, 
/** Acceso a las cadenas del archivo js a traducir **/
controllers/TranslateStringJsController.php
/**Contiene los Strings del archivo js, los cuales son traducidos por la funcion Yii::t() de yii2**/
components/TranslateStringJs.php
/**Implementacion de funcion para traducir los strings**/       
modified:   web/js/script/dashboard_index.js

Translate js in yii2

---

views/import/beneficiarios/step-3.php
views/import/beneficiarios/wizard.php
views/layouts/main.php

- Oculto el header /import
- Oculto el sidebar cuando me encuentre en /import
- Agregacion de clase css en el tab del wizard.php de la interfaz de importar beneficiarios
- Correccion en sintaxis php del archivo step-3.php

Hide sidebar header

---

controllers/ImportController.php
models/Event.php

- Identacion de codigo en archivo ImportarController
- Eliminacion de lineas comentariadas, echo 'Bene' y var_dump innecesario
- Correccion en la construccion del nombre del evento eliminando el signo $ donde no lo necesitaba

Fix importar

---

controllers/ImportController.php

correccion en lina 346, llamando valor del arreglo de manera incorrecta

Fix import save from 2record

---

controllers/ReportController.php

Escapando filtros con cadenas vacías ...
Archivo modificado:
controllers/ReportController.php

validacion de filtros, cuando no se seleccionan todos

---

controllers/ReportController.php

-identancion de codigo
-ordenamiento de organizacion implementadora y organizacion de contacto
-correccion de union de organizacion con contacto

Fix query report

---

controllers/ImportController.php
models/Contact.php
models/base/Contact.php

renombrando campo sex x sex_id
*PD:*
* CLEAR CACHE YII*
* php yii cache/flush-all *

renombrando campo sex x sex_id
